name: Build and deploy to Netlify

on:
  schedule:
    - cron: "0 8,20 * * *"

env:
  IMAGE_NAME: generate-enriched-bos-list
  NETLIFY_CLI_VERSION: 2.54.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build the Golang file
        run: docker build . --file Dockerfile --tag $IMAGE_NAME

      - name: Generate the JSON (+ copy web files)
        run: |
          mkdir -p build
          cp -r web/* build/
          docker run --rm -v `pwd`/build:/app/web $IMAGE_NAME

      - name: Publish to Netlify
        uses: netlify/actions/cli@master
        with:
          args: deploy --dir=build --prod
        env:
          NETLIFY_SITE_ID: ${{ secrets.SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}